# Generated by Django 4.2 on 2023-04-25 17:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LavaJato',
            fields=[
                ('id', models.UUIDField(blank=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('Nome', models.CharField(max_length=8)),
                ('Serviço', models.CharField(choices=[('Concerto', 'concerto'), ('lavagem completo', 'Lavagem Completo'), ('Lavagem + Cera', 'lavagem + cera')], max_length=30)),
                ('Funcionario', models.CharField(max_length=8)),
            ],
        ),
    ]
